### ISSUE TITLE
Crash in Twitch API

### ISSUE THREAD

**Issue by unlink2** [unlink2/memebotj#36]
`Exception in thread "#hitokage220" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 30.01017294 at line 1 column 150 path $.stream.average_fps
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:239)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:116)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at me.krickl.memebotj.Twitch.TwitchAPI.update(TwitchAPI.java:61)
	at me.krickl.memebotj.ChannelHandler.update(ChannelHandler.java:306)
	at me.krickl.memebotj.ChannelHandler.run(ChannelHandler.java:277)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: Expected an int but was 30.01017294 at line 1 column 150 path $.stream.average_fps
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1202)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:247)
	... 14 more`

**Comment by unlink2** [comment]
The exception is caught as of commit fc9b89b . The issue needs to be addressed further though.

**Comment by luigitus** [comment]
The issue is cause by the average_fps in the API, the Model is defined as an Integer, but Twitch sometimes returns the **exact** FPS.
We don't need that probably for a bot, so I removed it from the Model in the Pull request #37

**Comment by unlink2** [comment]
This did fix the issue. Cool :D . It was strange cause ti only happened in one channel.
